# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwent_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='art',
            field=models.TextField(default='nothing', max_length=1200),
            preserve_default=False,
        ),
    ]
